[package]
name = "whetstone-demo"
version = "1.0.0"
authors = ["Rowan Preston <rowan.t.preston@gmail.com>"]
edition = "2021"

[dependencies]
whetstone = { path = "../" }
log = "0.4.27"
env_logger = "0.11.8"
eframe = "0.31"
egui = "0.31.1"

[[bin]]
name = "whetstone-demo"
path = "src/demo.rs"
